ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - core-js-pure
  - es5-ext
  - esbuild
  - gatsby
  - gatsby-cli
  - lmdb
  - msgpackr-extract

onlyBuiltDependencies:
  - sharp
